name: 'Azure WebApp Container'
description: 'Deploy Container Web Apps to Azure'
inputs: 
  app-name:
    description: 'Name of the Azure Web App'
    required: true
  images:
    description: "Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)"
    required: true
  configuration-file:
    description: 'Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario'
    required: false
  container-command:
    description: 'Enter the start up command. For ex. dotnet run or dotnet filename.dll'
    required: false
outputs:
  webapp-url:
    description: 'URL to work with your webapp'
branding:
  icon: 'container-webapp.svg'
  color: 'blue'
runs:
  using: 'node'
  main: 'lib/main.js'